#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
#
%define short_name bs4
Name:       python3-beautifulsoup4

# >> macros
# << macros

Summary:    Screen-scraping library
Version:    4.4.1
Release:    1
Group:      Development/Languages/Python
License:    MIT
URL:        http://www.crummy.com/software/BeautifulSoup/bs4/
Source:    %{name}-%{version}.tar.gz
Requires:   python3-base
BuildRequires:   python3-base
BuildArch:      noarch
BuildRoot:      %{_tmppath}/%{name}-%{version}-build

%description
Beautiful Soup sits atop an HTML or XML parser, providing Pythonic idioms for iterating, searching, and modifying the parse tree.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
python3 -m pip install -t %{buildroot}/usr/lib/python3.4/site-packages/ beautifulsoup4-4.4.1-py3-none-any.whl

# >> install post
# << install post

%pre
# >> pre
# << pre

%preun
# >> preun
# << preun

%files
%defattr(-,root,root,-)
/usr/lib/python3.4/site-packages/bs4/*
/usr/lib/python3.4/site-packages/beautifulsoup4-4.4.1.dist-info/*
# >> files
# << files
